module.exports = {
  extends: ['airbnb-base'],
  parserOptions: {
    ecmaVersion: 2019,
    sourceType: 'module',
  },
  rules: {
    'arrow-parens': ['error', 'as-needed', { requireForBlockBody: false }],
    semi: ['error', 'never'],
    'max-len': ['error', { code: 120 }],
    camelcase: ['error', { properties: 'never', ignoreDestructuring: true }],
    'prefer-object-spread': ['error'],
    'no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    'no-invalid-this': 'off',
    'no-mixed-operators': [
      'error',
      {
        groups: [
          ['%', '**'],
          ['%', '+'],
          ['%', '-'],
          ['%', '*'],
          ['%', '/'],
          ['**', '+'],
          ['**', '-'],
          ['**', '*'],
          ['**', '/'],
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: true,
      },
    ],
    'no-param-reassign': ['error', { props: true, ignorePropertyModificationsFor: [] }],
    'no-restricted-syntax': ['error', 'ForInStatement', 'LabeledStatement', 'WithStatement'],
    'lines-between-class-members': 'off',
    'import/prefer-default-export': 'off',
    'import/no-default-export': 'error',
    'import/no-named-default': 'off',
  },
}
